defaults: &defaults
  working_directory: ~/repo
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build_prod:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5.6
    environment:
      BUNDLE_PATH: ~/repo/docs
    steps:
      - checkout
      - run:
          name: Install Ruby dependencies
          command: bundle check || bundle install
      - run:
          name: Build the Jekyll site
          command: bundle exec jekyll build
      - persist_to_workspace:
          root: ~/
          paths:
            - _site
  deploy_prod:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/build
      - aws-s3/sync:
          from: /tmp/build/_site
          to: 's3://resource-usermanual'
          arguments: |
            --delete
workflows:
  version: 2
  deploy:
    jobs:
      - build_prod:
          name: build
          context: TCL
          filters:
            branches:
              only: master          
      - deploy_prod:
          name: deploy
          context: TCL
          requires:
            - build
          filters:
            branches:
              only: master